### ISSUE TITLE
ローカル環境で募集フォームにスタイルシートを当てる方法が知りたい

### ISSUE THREAD

**Issue by horaotoko** [ruby-no-kai/sponsor-app#4]
<img width="1276" alt="2018-11-22 0 14 08" src="https://user-images.githubusercontent.com/953660/48850268-9fdda280-edeb-11e8-8538-1066ac978b20.png">

herokuの確認環境みたいにフォームのページがなかったのでスタイル当てられず...
ローカル環境でスタイルシートを当てるまでのやり方を教えてください！

**Comment by amatsuda** [comment]
resolved via https://github.com/ruby-no-kai/rubykaigi.org/issues/476
